In [ ]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
axbend = pd.read_csv('axbend.csv', delimiter=" ")
axbend = axbend.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
axbend = axbend.add_suffix('ad')
axbend = axbend.rename(columns={'V1ad':'ID'})
axbend

buckle = pd.read_csv('buckle.csv', delimiter=" ")
buckle = buckle.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
buckle = buckle.add_suffix('be')


inclin = pd.read_csv('inclin.csv', delimiter=" ")
inclin = inclin.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
inclin = inclin.add_suffix('in')


opening = pd.read_csv('opening.csv', delimiter=" ")
opening = opening.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
opening = opening.add_suffix('og')


propel = pd.read_csv('propel.csv', delimiter=" ")
propel = propel.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
propel = propel.add_suffix('pl')


rise = pd.read_csv('rise.csv', delimiter=" ")
rise = rise.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
rise = rise.add_suffix('re')


roll = pd.read_csv('roll.csv', delimiter=" ")
roll = roll.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
roll = roll.add_suffix('rl')


shear = pd.read_csv('shear.csv', delimiter=" ")
shear = shear.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
shear = shear.add_suffix('sr')


shift = pd.read_csv('shift.csv', delimiter=" ")
shift = shift.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
shift = shift.add_suffix('st')


slide = pd.read_csv('slide.csv', delimiter=" ")
slide = slide.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
slide = slide.add_suffix('se')


stagger = pd.read_csv('stagger.csv', delimiter=" ")
stagger = stagger.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
stagger = stagger.add_suffix('sg')


stretch = pd.read_csv('stretch.csv', delimiter=" ")
stretch = stretch.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
stretch = stretch.add_suffix('sh')


tilt = pd.read_csv('tilt.csv', delimiter=" ")
tilt = tilt.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
tilt = tilt.add_suffix('tt')


tip = pd.read_csv('tip.csv', delimiter=" ")
tip = tip.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
tip = tip.add_suffix('tp')


twist = pd.read_csv('twist.csv', delimiter=" ")
twist = twist.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
twist = twist.add_suffix('tw')


xdisp = pd.read_csv('xdisp.csv', delimiter=" ")
xdisp = xdisp.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
xdisp = xdisp.add_suffix('xp')


ydisp = pd.read_csv('ydisp.csv', delimiter=" ")
ydisp = ydisp.rename({'V1': '3', 'V2': '4', 'V3': '5', 'V4': '6','V5': '7', 'V6': '8','V7': '9', 'V8': '10','V9': '11', 'V10': '12','V11': '13', 'V12': '14','V13': '15', 'V14': '16','V15': '17', 'V16': '18', 'V17': '19', 'V18': '20', 'V19': '21', 'V20': '22', 'V21': '23'}, axis='columns')
ydisp = ydisp.add_suffix('yp')


merged_df = pd.concat([axbend, buckle, inclin, opening, propel, rise, roll, shear, shift, slide, stagger, stretch, tilt, tip, twist, xdisp, ydisp], axis="columns")
pd.set_option('display.max_columns', None)
merged_df

ID = ["A157A", "A157B", "A157C", "A158A", "A158B", "A158C", "A170A", "A170B", "A170C", "A186A", "A186B", "A186C", "A196A", "A196B", "A196C", "A213A", "A213B", "A213C", "A245A", "A245B", "A245C", "A248A","A248B", "A248C", "A267A", "A267B", "A267C", "A273A", "A273B", "A273C", "A282A", "A282B", "A282C", "A290A", "A290B", "A290C", "C157A", "C157B", "C157C", "C158A", "C158B", "C158C", "C170A", "C170B", "C170C", "C186A", "C186B", "C186C", "C202A", "C202B", "C202C", "C213A", "C213B", "C213C", "C245A", "C245B", "C245C", "C248A","C248B", "C248C", "C267A", "C267B", "C267C", "C273A", "C273B", "C273C", "C282A", "C282B", "C282C", "C290A", "C290B", "C290C"]
column_names = list(merged_df.columns.values)
outcome_df = ['C*', 'C*', 'C*', 'C*', 'C*', 'C*', 'NC*', 'NC*', 'NC*', 'NC*', 'NC*', 'NC*', 'NC*', 'NC*', 'NC*', 'NC*', 'NC*', 'NC*', 'C*', 'C*', 'C*', 'C*', 'C*', 'C*', 'NC*', 'NC*', 'NC*', 'C*', 'C*', 'C*', 'C*', 'C*', 'C*', 'NC*', 'NC*', 'NC*', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'NC', 'NC', 'NC', 'NC', 'NC', 'NC', 'NC', 'NC', 'NC', 'NC', 'NC', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'NC', 'NC', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'NC', 'NC']
total_data = merged_df.assign(Outcome=outcome_df)
total_data

,3ad,4ad,5ad,6ad,7ad,8ad,9ad,10ad,11ad,12ad,13ad,14ad,15ad,16ad,17ad,18ad,19ad,20ad,21ad,22ad,23ad,3be,4be,5be,6be,7be,8be,9be,10be,11be,12be,13be,14be,15be,16be,17be,18be,19be,20be,21be,22be,23be,3in,4in,5in,6in,7in,8in,9in,10in,11in,12in,13in,14in,15in,16in,17in,18in,19in,20in,21in,22in,23in,3og,4og,5og,6og,7og,8og,9og,10og,11og,12og,13og,14og,15og,16og,17og,18og,19og,20og,21og,22og,23og,3pl,4pl,5pl,6pl,7pl,8pl,9pl,10pl,11pl,12pl,13pl,14pl,15pl,16pl,17pl,18pl,19pl,20pl,21pl,22pl,23pl,3re,4re,5re,6re,7re,8re,9re,10re,11re,12re,13re,14re,15re,16re,17re,18re,19re,20re,21re,22re,23re,3rl,4rl,5rl,6rl,7rl,8rl,9rl,10rl,11rl,12rl,13rl,14rl,15rl,16rl,17rl,18rl,19rl,20rl,21rl,22rl,23rl,3sr,4sr,5sr,6sr,7sr,8sr,9sr,10sr,11sr,12sr,13sr,14sr,15sr,16sr,17sr,18sr,19sr,20sr,21sr,22sr,23sr,3st,4st,5st,6st,7st,8st,9st,10st,11st,12st,13st,14st,15st,16st,17st,18st,19st,20st,21st,22st,23st,3se,4se,5se,6se,7se,8se,9se,10se,11se,12se,13se,14se,15se,16se,17se,18se,19se,20se,21se,22se,23se,3sg,4sg,5sg,6sg,7sg,8sg,9sg,10sg,11sg,12sg,13sg,14sg,15sg,16sg,17sg,18sg,19sg,20sg,21sg,22sg,23sg,3sh,4sh,5sh,6sh,7sh,8sh,9sh,10sh,11sh,12sh,13sh,14sh,15sh,16sh,17sh,18sh,19sh,20sh,21sh,22sh,23sh,3tt,4tt,5tt,6tt,7tt,8tt,9tt,10tt,11tt,12tt,13tt,14tt,15tt,16tt,17tt,18tt,19tt,20tt,21tt,22tt,23tt,3tp,4tp,5tp,6tp,7tp,8tp,9tp,10tp,11tp,12tp,13tp,14tp,15tp,16tp,17tp,18tp,19tp,20tp,21tp,22tp,23tp,3tw,4tw,5tw,6tw,7tw,8tw,9tw,10tw,11tw,12tw,13tw,14tw,15tw,16tw,17tw,18tw,19tw,20tw,21tw,22tw,23tw,3xp,4xp,5xp,6xp,7xp,8xp,9xp,10xp,11xp,12xp,13xp,14xp,15xp,16xp,17xp,18xp,19xp,20xp,21xp,22xp,23xp,3yp,4yp,5yp,6yp,7yp,8yp,9yp,10yp,11yp,12yp,13yp,14yp,15yp,16yp,17yp,18yp,19yp,20yp,21yp,22yp,23yp,Outcome
1,7.9,7.9,7.7,8.9,8.4,9.0,10.6,14.8,17.8,20.6,24.4,27.6,24.0,20.4,16.5,12.6,10.7,10.6,10.2,8.0,6.9,-5.9,3.5,12.1,0.6,26.4,3.6,4.9,2.5,2.8,1.3,5.8,2.2,1.6,-0.4,1.1,2.5,-3.9,-3.0,-10.3,-14.0,-17.8,42.6,-82.5,-78.6,-1.9,-29.2,35.1,4.3,-30.2,14.9,21.0,-19.7,-10.3,-11.9,19.6,17.3,-10.0,22.7,17.9,20.9,36.9,40.5,69.8,131.3,-143.7,49.9,4.7,18.0,87.8,152.4,-135.6,-69.7,1.0,70.5,137.4,-149.7,-84.8,-13.5,46.4,96.0,143.7,-128.3,-65.5,18.4,25.0,-32.6,79.1,-166.4,-5.8,-4.5,0.8,-11.2,-11.0,-7.2,-4.1,3.6,-11.4,-12.3,-2.7,5.8,16.0,30.8,-38.0,-38.9,0.27,0.14,1.00,2.86,0.71,0.27,0.31,0.20,0.18,0.24,0.22,0.24,0.22,0.21,0.22,0.21,0.39,0.31,0.23,0.24,0.31,-4.1,-0.5,50.6,-62.0,58.4,-3.6,0.9,-0.8,-3.4,2.1,-3.9,3.7,0.1,-3.9,2.3,-3.4,-9.2,-9.3,-3.7,1.4,5.4,2.09,0.04,0.64,4.88,17.61,0.42,0.16,0.63,0.11,-0.07,0.01,0.07,-0.41,0.75,0.50,-0.18,-0.35,-1.67,-6.01,2.27,2.16,1.24,-0.13,3.00,-3.22,-0.08,-0.25,0.64,-0.08,-0.48,0.11,-0.14,0.48,-0.13,-0.72,0.29,-0.06,1.59,0.65,0.10,-1.31,-0.57,-0.42,-0.09,2.37,-0.39,-1.92,-0.02,0.22,-0.02,-0.45,0.24,-0.28,0.52,0.05,-0.06,-0.07,0.03,0.63,0.17,0.11,0.53,1.05,-58.25,-48.98,-48.87,-25.60,-8.32,-32.20,-25.78,-18.86,-13.15,-6.44,0.09,6.81,13.35,19.41,26.00,32.53,39.00,44.50,48.23,49.98,58.40,-20.83,-25.08,0.18,-14.84,2.89,-3.25,-3.94,-4.32,0.30,0.78,0.01,-0.57,0.02,2.98,2.86,3.15,3.09,-2.87,1.84,23.79,21.17,5.5,4.8,9.1,-22.5,4.6,0.3,0.4,4.3,-1.6,3.1,-1.1,1.7,3.5,0.8,2.3,1.0,-3.2,4.7,-1.6,-3.4,-5.1,161.0,-21.2,-145.0,-101.8,-100.1,102.7,103.4,-109.8,112.8,128.0,-31.3,167.2,71.6,167.3,139.0,-42.9,155.3,139.0,159.3,25.0,41.1,-0.3,-174.3,-28.0,-37.1,3.1,0.9,1.4,-178.5,0.8,1.3,1.6,0.2,-178.1,1.3,1.7,1.7,-5.2,-9.0,-176.9,0.6,0.8,0.01,0.02,0.07,-0.15,-0.82,0.03,0.09,-0.05,0.01,0.08,-0.05,-0.01,-0.01,0.09,0.32,-0.24,0.57,0.31,-0.18,0.02,0.08,0.38,0.25,-0.52,-0.40,-0.60,-0.39,-0.28,-0.14,0.13,-0.07,-0.07,-0.13,0.03,0.23,0.31,0.41,0.81,1.66,1.76,-1.69,-2.19,C*
2,11.6,11.1,10.3,11.1,9.3,9.7,11.0,15.0,17.7,20.1,23.1,26.1,24.0,21.4,17.6,13.3,11.5,11.5,11.4,9.0,7.7,-9.2,5.8,36.7,37.7,28.5,3.3,4.7,2.3,2.3,1.8,5.4,2.5,1.5,-0.6,0.9,3.6,-4.2,-8.6,-15.7,-15.0,-20.1,30.3,-56.1,-97.3,-14.0,-31.0,17.2,26.1,-29.7,14.1,21.4,-15.0,-13.7,-11.7,20.1,17.8,-15.2,25.1,30.8,32.6,39.4,49.2,78.4,141.3,-135.0,58.1,-2.2,15.9,86.9,151.3,-136.2,-69.4,0.7,70.3,138.1,-148.6,-84.5,-11.2,47.6,94.2,134.7,-138.3,-74.5,14.3,18.2,-33.7,33.8,-158.7,-3.1,-3.5,3.7,-12.7,-11.0,-6.7,-2.9,3.8,-13.3,-14.9,-5.1,3.3,12.9,34.8,-35.0,-36.1,0.26,0.14,2.60,2.37,0.72,0.26,0.30,0.22,0.18,0.24,0.22,0.24,0.21,0.20,0.22,0.21,0.34,0.33,0.25,0.25,0.31,-5.5,0.7,43.6,-63.4,67.3,-3.4,1.4,-2.3,-3.3,1.9,-3.8,3.4,0.8,-4.2,2.7,-3.5,-9.9,-7.9,-7.0,1.9,4.8,2.40,-0.16,9.61,2.69,17.52,0.48,0.08,0.72,0.00,-0.03,0.01,0.05,-0.44,0.71,0.49,-0.19,-0.63,-3.15,-7.77,2.89,3.07,1.21,-0.14,3.65,-3.87,-0.03,-0.15,0.69,0.01,-0.49,-0.01,-0.02,0.48,-0.19,-0.75,0.21,-0.14,1.56,0.72,0.18,-1.23,-0.55,-0.66,0.02,4.02,-2.36,-1.90,0.06,0.19,-0.02,-0.38,0.29,-0.33,0.44,0.04,-0.07,-0.11,0.01,0.84,0.44,-0.01,0.79,1.21,-57.62,-48.61,-49.76,-26.67,-8.56,-32.27,-25.82,-18.88,-13.14,-6.45,0.11,6.81,13.36,19.40,26.00,32.62,39.07,44.78,49.32,49.47,57.91,-24.85,-27.37,5.87,-33.20,6.59,-2.78,-3.80,-4.34,0.15,0.67,0.01,-0.48,0.10,2.88,2.55,2.73,2.75,-4.23,-2.18,26.28,23.85,3.5,1.4,51.3,-77.4,5.6,1.3,1.1,5.4,-1.5,2.1,-0.4,1.7,2.6,0.3,1.6,1.0,-3.7,5.2,-1.7,-3.3,-5.0,160.1,-1.8,-132.4,-112.8,-107.3,115.7,102.5,-87.1,126.5,140.3,-24.3,130.0,41.9,173.3,152.1,-26.0,161.2,147.6,161.1,12.9,36.3,-0.3,-175.2,-52.7,-2.3,7.2,0.6,1.3,-178.2,0.6,1.4,1.5,0.4,-178.1,1.3,1.4,1.9,-5.0,-6.9,-178.2,0.6,1.0,-0.02,0.04,0.49,0.17,-0.80,-0.00,0.06,-0.04,0.02,0.08,-0.06,-0.00,0.00,0.08,0.35,-0.36,0.64,0.33,-0.23,0.01,-0.00,-0.38,-0.32,-0.60,0.87,-1.12,-0.52,-0.32,-0.14,0.08,-0.09,-0.04,-0.11,0.01,0.27,0.43,0.52,0.96,1.93,2.33,-1.96,-2.31,C*
3,6.9,6.5,6.2,7.8,8.3,9.9,11.5,15.4,18.2,20.2,23.6,26.9,23.6,20.8,17.6,13.6,11.7,11.4,10.8,8.2,7.0,-8.4,16.9,36.2,3.9,28.2,2.7,5.7,2.7,2.9,1.5,5.6,2.5,2.1,0.9,1.6,2.4,-4.5,-5.6,-8.3,-13.8,-20.7,83.2,-103.6,-96.7,3.0,-27.3,18.6,10.3,-33.9,9.9,18.1,-15.4,-10.2,-13.1,14.8,10.7,-9.8,20.2,24.2,22.0,32.2,48.0,84.8,144.6,-129.6,74.8,-7.8,17.3,87.3,152.8,-135.3,-70.2,1.1,71.1,137.2,-150.3,-84.8,-13.4,46.3,91.7,125.4,-142.0,-80.0,14.1,20.9,-24.3,55.8,-149.1,-2.9,-3.9,0.2,-12.0,-11.9,-7.6,-4.9,4.2,-11.8,-14.2,-3.9,4.8,12.6,31.1,-29.3,-32.0,0.28,0.46,2.94,1.55,0.86,0.26,0.30,0.22,0.17,0.24,0.22,0.24,0.22,0.21,0.22,0.21,0.34,0.72,0.31,0.26,0.33,-4.5,-1.0,45.5,-76.7,71.2,-4.1,-0.0,-2.2,-3.1,2.7,-3.9,2.2,0.7,-3.9,3.0,-2.7,-8.6,-6.1,2.2,1.8,5.6,2.38,-3.30,7.68,5.72,19.92,0.74,0.04,0.65,0.13,-0.03,0.01,0.05,-0.40,0.58,0.46,-0.21,-0.22,-2.20,-6.13,3.35,3.45,1.09,-0.10,2.57,-2.49,0.02,-0.29,0.72,-0.04,-0.50,0.17,-0.20,0.49,-0.13,-0.77,0.21,-0.04,1.55,0.68,-0.45,-1.10,-0.65,-0.62,0.02,4.45,-2.60,-1.96,-0.07,0.06,-0.01,-0.36,0.22,-0.25,0.41,0.03,0.07,-0.02,0.10,1.08,0.47,-0.10,0.75,0.96,-58.04,-48.72,-49.60,-33.77,-10.44,-32.26,-25.83,-18.89,-13.17,-6.46,0.06,6.84,13.34,19.48,26.04,32.56,38.98,44.98,50.09,49.98,58.05,-24.52,-28.08,9.61,-26.53,11.12,-2.76,-3.87,-4.25,0.22,0.82,0.02,-0.68,-0.06,2.94,2.74,3.27,3.61,-3.12,-4.36,24.94,24.24,5.2,-0.7,32.2,-76.9,7.6,1.4,0.5,3.5,-1.7,3.2,-1.9,1.9,3.2,0.6,2.2,1.3,-3.2,1.8,8.3,-2.4,-4.8,-165.1,-16.2,-114.5,-135.4,-105.5,108.8,109.8,-98.5,121.3,134.6,-30.5,111.2,77.8,162.7,138.6,-25.8,158.2,151.4,154.8,1.4,32.6,0.1,-174.9,-72.2,-23.1,15.3,0.8,1.4,-178.4,0.7,1.4,1.7,0.6,-177.7,1.4,1.8,1.8,-3.3,-9.3,-177.5,1.0,1.0,-0.06,0.45,0.07,-0.43,-1.60,-0.00,0.11,-0.05,0.03,0.05,-0.03,-0.01,-0.02,0.09,0.24,-0.25,0.45,0.11,0.01,-0.09,-0.06,0.69,0.40,-0.98,1.26,-1.11,-0.49,-0.29,-0.15,0.07,-0.09,-0.04,-0.10,0.03,0.16,0.30,0.40,0.78,1.86,1.99,-1.65,-2.06,C*
4,6.8,7.3,7.5,9.7,11.1,11.4,11.8,14.8,17.0,20.6,24.1,23.9,21.2,19.2,18.4,16.1,13.4,11.0,9.9,8.5,8.2,-16.3,21.2,26.1,153.2,17.6,6.4,-2.7,2.3,2.1,3.0,3.5,3.0,0.0,-2.9,5.9,-2.0,-3.1,-2.3,-22.7,-1.6,10.6,68.8,-84.4,-90.2,-58.3,-21.5,81.2,45.6,-47.3,20.0,-0.8,-4.1,-23.2,-13.2,16.6,-2.7,12.0,21.5,15.7,35.9,-0.7,-43.2,68.1,127.2,-143.3,31.6,-2.8,15.6,84.5,152.3,-130.8,-64.0,1.8,66.8,132.2,-152.1,-82.7,-12.3,47.7,99.6,142.5,-130.9,-66.9,14.9,15.5,-25.1,22.1,-165.7,-7.5,7.2,8.2,-11.8,-7.1,-8.5,1.5,14.2,-12.3,-12.3,-4.3,-2.2,8.2,28.7,-33.9,-32.2,0.28,0.38,2.13,3.22,0.48,0.25,0.19,0.22,0.26,0.22,0.19,0.23,0.16,0.26,0.26,0.21,0.34,0.28,0.28,0.25,0.35,-5.2,-3.2,36.8,-61.9,69.3,-5.2,-1.4,-1.7,-1.0,-2.7,6.0,-5.8,-0.4,2.5,-3.0,-4.6,-9.6,-10.9,0.3,2.6,-1.5,2.93,-4.07,4.81,0.76,12.72,0.62,0.78,0.12,-0.35,0.01,-0.00,0.21,-0.14,0.53,0.74,0.05,-1.13,-2.26,-12.53,2.35,4.07,0.67,-0.08,4.70,-4.69,-0.24,0.56,0.20,-0.10,-0.47,-0.60,0.52,0.54,-0.10,-0.24,-0.47,0.18,1.39,0.55,-0.23,-0.78,-0.52,-0.48,0.03,3.65,-2.37,-1.67,-0.21,-0.00,0.01,0.70,-0.47,0.51,-0.71,0.08,-0.06,0.20,-0.17,0.87,0.25,-0.00,0.50,0.68,-61.05,-50.85,-49.12,-19.99,-6.08,-32.26,-25.94,-19.03,-12.83,-6.39,0.08,6.59,13.03,19.72,26.19,32.72,38.89,44.35,47.67,53.30,60.19,-16.03,-24.06,5.62,-37.01,3.00,-3.63,-3.68,-4.60,1.01,0.70,0.03,-0.11,0.82,1.97,1.70,2.18,2.70,-3.66,-0.31,20.58,18.37,7.8,1.4,60.7,-73.5,6.4,1.6,0.6,3.9,1.4,1.5,4.2,0.8,2.2,2.7,0.3,2.9,-3.5,6.1,3.6,-1.7,0.3,129.1,-25.5,-132.2,-98.1,-104.6,93.8,96.2,-114.3,-141.5,-89.7,75.0,-44.6,51.3,116.2,-157.0,157.7,157.2,129.6,165.6,-167.5,-151.2,-0.4,-176.9,-37.4,5.4,0.0,0.9,0.5,-178.8,1.0,0.9,0.4,0.2,-179.1,0.8,1.4,0.1,-3.6,-7.2,-177.1,1.3,2.6,-0.29,0.68,0.23,0.36,-0.40,-0.03,0.01,-0.03,0.04,0.00,0.00,-0.05,0.01,0.01,0.03,0.25,0.48,0.32,-0.31,-0.04,-0.04,0.95,0.70,-1.28,1.19,-0.77,-0.48,-0.33,-0.19,-0.03,0.02,-0.17,0.00,-0.17,0.19,0.36,0.62,0.77,1.52,1.65,-1.34,-1.27,C*
5,9.1,10.3,9.3,10.8,10.9,10.0,10.1,13.9,17.6,21.1,24.7,24.5,22.1,20.4,18.6,14.7,12.2,11.0,12.3,11.3,10.6,-11.5,10.7,15.6,1.4,35.0,6.6,-3.3,2.8,-0.1,2.6,3.6,3.1,0.0,-2.0,4.1,-1.6,-3.1,3.0,-13.9,-5.6,7.0,42.9,-58.1,-84.7,46.3,-54.7,72.7,59.0,-56.0,37.7,0.9,-6.8,-26.2,-10.3,20.1,1.1,12.9,18.5,-0.4,21.1,14.8,-21.2,76.7,133.7,-141.7,24.1,-7.6,15.5,83.9,153.9,-130.7,-62.8,2.5,65.5,132.1,-153.4,-82.4,-12.5,46.5,97.8,146.0,-135.3,-73.8,16.8,19.8,-30.3,39.4,-134.4,-5.6,7.2,7.3,-11.0,-8.7,-8.4,1.8,15.5,-13.2,-12.1,-5.2,-4.0,4.7,21.8,-30.8,-36.9,0.27,0.24,2.28,1.93,0.95,0.27,0.20,0.21,0.27,0.22,0.19,0.24,0.16,0.26,0.25,0.22,0.35,0.30,0.29,0.24,0.36,-3.4,-5.3,31.8,-77.3,66.4,-5.7,-1.5,-1.0,-2.2,-3.3,6.3,-5.7,-0.4,1.9,-1.8,-3.6,-8.3,-10.3,4.4,-0.9,-1.1,2.68,-1.60,4.04,8.95,22.54,1.41,0.73,0.20,-0.74,-0.12,-0.01,0.06,-0.16,0.80,0.59,0.26,-0.48,-0.61,-10.40,2.65,3.68,0.67,-0.05,3.48,-3.20,-0.33,0.34,0.31,-0.13,-0.29,-0.55,0.49,0.35,-0.10,-0.34,-0.27,-0.09,1.17,0.39,-0.27,-0.77,-0.67,-0.08,0.10,3.20,-2.62,-1.74,-0.21,0.09,-0.02,0.47,-0.45,0.49,-0.48,0.10,-0.16,0.21,-0.18,0.90,0.26,-0.09,0.10,0.27,-61.20,-51.28,-49.54,-30.54,-13.42,-32.10,-25.79,-18.79,-12.68,-6.25,0.04,6.53,13.03,19.61,26.25,32.64,38.81,44.45,48.12,53.20,60.24,-14.29,-22.23,0.83,-19.29,12.05,-4.19,-4.21,-5.09,1.60,0.82,0.03,-0.06,0.48,2.54,1.61,2.78,3.06,-2.63,1.20,18.11,17.13,8.2,0.2,32.5,-63.5,13.2,1.5,0.9,3.9,1.3,3.3,3.8,0.5,3.1,1.1,1.9,2.5,-2.6,5.9,4.5,-1.7,-0.3,123.9,-21.3,-131.0,-75.6,-116.2,-95.2,82.0,-129.8,163.9,-97.2,64.1,-45.6,65.2,-161.1,-154.7,156.5,158.8,96.8,162.3,54.3,-144.4,-0.3,-174.9,-42.1,1.1,15.2,1.5,0.5,-178.8,1.4,1.1,0.3,1.2,-179.1,0.8,1.5,0.1,-2.7,-8.2,-175.6,0.8,2.6,-0.06,0.34,0.13,-0.30,-1.32,-0.16,0.02,-0.04,0.08,0.03,0.00,-0.05,0.01,0.02,0.06,0.23,0.26,0.23,-0.08,-0.05,-0.15,0.58,0.42,-0.71,0.40,-0.69,-0.40,-0.34,-0.22,0.01,-0.01,-0.19,-0.00,-0.12,0.17,0.21,0.38,0.42,1.05,1.20,-0.71,-0.80,C*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,10.9,8.9,9.6,11.7,12.5,12.8,13.4,15.9,17.2,19.5,25.4,26.6,22.1,17.1,14.1,12.3,11.5,10.9,10.4,8.6,8.1,-1.8,6.8,3.2,17.5,3.3,0.5,3.0,-0.0,1.5,0.7,4.9,4.0,-0.1,0.2,-2.7,-1.2,8.7,-5.0,0.6,-2.1,-2.2,14.5,-43.0,-21.6,-39.6,34.7,11.0,-4.7,-8.4,6.8,6.6,-6.4,-16.0,-7.1,7.4,19.3,12.9,-21.4,15.0,1.2,11.6,10.9,43.2,112.6,-177.6,-6.3,-50.3,19.7,89.7,156.6,-129.3,-64.0,1.3,68.8,130.8,-153.9,-87.7,-17.9,55.7,112.1,-178.6,-107.8,-40.5,-6.2,-4.4,-1.2,174.9,-11.7,-6.7,-6.6,0.2,-6.3,-11.4,-7.7,-3.2,12.8,-17.4,-13.1,-9.1,-5.4,10.1,2.3,-19.0,-13.1,0.28,0.24,1.15,1.27,0.25,0.32,0.28,0.24,0.25,0.26,0.22,0.20,0.17,0.22,0.22,0.24,0.26,0.18,0.17,0.27,0.27,-2.4,-0.1,13.9,-16.4,-1.0,-0.4,4.3,0.2,3.4,-4.4,4.2,-0.3,-4.6,1.4,2.5,-2.5,-4.5,-0.8,-3.8,2.1,0.7,1.01,0.18,3.92,-13.48,0.40,-0.10,0.43,0.90,-0.34,-0.11,0.02,-0.01,-0.15,0.76,0.50,0.80,-1.01,-1.87,0.92,1.80,1.27,0.42,0.16,0.40,-2.41,-0.31,0.47,0.50,-0.17,-0.29,0.15,-0.22,0.35,-0.06,-0.49,-0.51,0.30,0.24,0.31,-0.34,-0.41,-0.20,-0.08,-0.27,-1.21,1.07,0.27,0.18,0.31,-0.04,0.20,-0.13,0.19,-0.27,0.10,-0.19,-0.21,-0.22,-0.31,-0.05,0.34,0.20,0.37,-64.06,-57.00,-49.57,0.29,-39.12,-32.65,-25.72,-18.93,-12.54,-6.55,0.06,6.74,13.17,19.41,25.92,32.77,39.45,44.99,50.59,57.48,64.49,-6.40,-7.95,-0.29,1.32,-4.09,-3.54,-3.05,-3.36,2.62,1.15,0.04,-0.83,-0.50,2.95,3.61,1.29,1.05,4.64,4.41,6.27,4.38,0.8,3.7,8.4,21.6,-1.1,-2.8,0.8,1.4,5.0,2.0,1.7,0.4,3.0,1.9,-2.4,0.7,5.1,2.0,-0.4,-0.8,-0.6,-95.2,40.7,-178.6,135.5,-59.9,-142.1,-72.0,80.7,138.8,177.1,70.7,-37.0,-82.8,-78.1,-178.8,-149.1,4.1,156.7,-1.1,-121.8,-88.9,0.8,177.4,-8.5,18.7,0.9,0.5,1.0,-179.1,1.3,1.9,1.3,0.5,-178.5,1.0,0.8,0.8,2.3,-177.8,-4.3,1.5,0.7,0.01,0.03,0.02,0.49,-0.11,0.06,-0.08,0.01,0.06,0.09,0.00,-0.01,0.01,-0.03,0.07,0.12,-0.19,0.07,0.00,-0.06,-0.12,0.03,0.08,-0.07,-0.69,-0.06,0.00,0.03,0.13,-0.09,-0.04,-0.11,-0.02,-0.10,0.17,0.14,0.11,0.09,0.15,0.04,-0.08,-0.08,C
69,11.7,9.9,10.8,12.7,12.6,12.5,13.0,15.5,16.5,19.0,24.6,25.8,22.3,17.8,14.4,12.5,11.5,10.7,10.1,8.1,7.8,2.2,6.6,0.2,15.2,2.9,0.3,3.2,2.4,3.1,1.3,4.4,4.2,-0.2,0.3,-1.4,-0.0,6.5,-0.6,1.1,-0.3,-1.7,-16.5,-42.1,-2.5,-47.1,25.5,13.6,0.7,-18.7,5.5,4.9,-6.4,-16.6,-8.2,7.6,12.7,7.0,-11.9,0.0,0.3,2.8,4.4,41.8,109.5,178.8,-7.4,-51.0,18.6,87.6,154.0,-131.8,-64.8,1.2,69.0,133.1,-151.5,-85.4,-16.9,55.7,116.2,-174.9,-105.0,-38.9,-6.9,-5.1,1.0,171.6,-12.7,-8.9,-7.9,1.0,-9.6,-11.4,-5.9,-2.5,13.8,-16.2,-13.5,-9.8,-5.1,8.9,-1.0,-18.3,-12.1,0.27,0.26,0.92,1.31,0.25,0.32,0.28,0.23,0.27,0.24,0.22,0.20,0.17,0.21,0.20,0.24,0.25,0.17,0.18,0.27,0.27,-1.9,0.9,23.9,-31.5,-1.4,-0.3,2.6,1.5,1.6,-2.7,3.5,-2.1,-4.2,1.0,3.0,-2.3,-3.5,0.5,-1.7,2.3,0.0,1.43,0.18,3.47,-14.99,0.26,-0.35,0.74,0.37,-0.18,-0.25,0.01,-0.03,-0.17,0.82,0.14,0.51,-0.45,-1.10,0.21,1.83,1.61,0.26,0.31,0.03,-2.34,-0.23,0.37,0.33,-0.11,-0.56,0.24,-0.28,0.59,-0.09,-0.31,-0.43,0.24,0.20,0.25,-0.48,-0.26,-0.24,-0.05,-0.24,-1.31,1.24,0.11,0.03,0.16,-0.04,0.26,-0.24,0.32,-0.32,0.08,-0.02,-0.04,-0.06,-0.32,-0.07,0.30,0.18,0.43,-64.03,-57.18,-49.60,0.90,-39.17,-32.62,-25.67,-19.07,-12.75,-6.50,0.05,6.69,13.10,19.58,25.90,32.65,39.33,45.01,50.85,57.79,64.39,-3.20,-6.38,-0.78,1.92,-3.29,-2.76,-2.40,-3.10,1.69,1.02,0.04,-0.61,0.26,2.17,3.54,1.78,1.29,4.36,3.58,4.56,4.64,2.3,2.4,20.0,32.1,-1.5,-2.5,0.9,1.2,3.3,2.2,1.9,0.9,2.4,4.4,-1.8,0.4,4.2,1.7,0.0,1.0,-0.1,10.3,21.7,-169.2,132.5,-57.9,-116.4,-37.1,134.9,-164.4,-160.6,38.5,-30.8,-121.9,-36.5,171.8,-160.6,-3.1,132.3,1.1,-160.3,-120.1,1.9,-5.6,-12.9,20.4,0.7,0.9,1.4,-178.8,1.3,1.4,1.3,0.5,-178.8,0.9,0.6,0.7,2.0,-178.9,0.6,2.5,0.6,-0.02,0.01,-0.01,0.48,-0.12,0.03,-0.07,-0.00,0.05,0.06,0.04,-0.02,0.02,-0.03,0.01,0.09,-0.17,0.05,-0.01,-0.00,-0.05,-0.12,-0.00,-0.09,-0.65,0.04,0.05,0.02,0.04,-0.03,0.02,-0.09,0.02,-0.06,0.06,0.06,0.06,0.07,0.05,0.05,-0.02,0.01,C
70,12.0,9.4,9.1,10.2,10.6,12.2,14.6,17.6,17.3,18.1,23.4,26.1,22.0,15.9,12.4,11.1,11.2,10.8,10.7,9.2,8.2,-2.1,3.9,6.5,21.0,3.6,3.0,2.8,-0.0,2.2,2.9,4.2,4.2,3.4,1.9,1.5,0.8,3.5,-2.3,0.4,-2.2,-1.2,-1.7,-8.3,-45.9,-15.3,31.1,4.5,-14.9,-5.0,8.2,11.5,-4.6,-16.7,-18.7,4.1,4.1,3.5,-1.6,6.7,0.8,20.6,9.6,49.7,117.5,-172.3,-9.0,-40.2,27.0,91.1,156.5,-132.5,-64.0,3.6,70.5,134.7,-153.3,-87.7,-25.0,43.7,108.0,173.9,-111.5,-46.2,-12.1,-5.7,-2.7,169.9,-9.0,-10.8,4.0,10.9,-5.9,-10.7,-13.8,-7.5,-4.0,-0.9,-8.1,-0.5,-2.0,8.4,8.9,-12.5,-8.3,0.31,0.27,1.17,1.49,0.27,0.32,0.24,0.22,0.25,0.23,0.23,0.25,0.24,0.25,0.23,0.21,0.25,0.20,0.21,0.30,0.30,-1.9,3.6,25.3,-29.4,-1.2,1.0,-1.3,1.8,2.1,1.9,0.6,1.0,0.5,1.9,-2.8,1.9,-1.0,-5.0,-2.9,-5.1,0.0,-2.12,3.72,4.76,-16.11,0.88,-0.42,0.95,0.20,-0.01,-0.05,0.01,-0.05,0.05,0.26,0.06,0.15,-1.05,-1.18,0.94,2.91,-0.20,0.47,0.13,0.68,-2.50,0.03,0.24,0.43,-0.07,-0.69,-0.26,0.25,0.69,-0.20,-0.45,-0.17,-0.07,0.38,0.29,-0.24,-0.54,0.10,0.15,0.02,-1.12,1.23,-0.05,0.07,-0.06,-0.12,0.12,0.06,0.01,-0.16,-0.06,0.07,-0.02,0.09,-0.32,0.18,-0.06,-0.18,0.00,-63.91,-56.80,-50.32,1.62,-39.01,-32.68,-26.18,-19.39,-13.09,-6.53,-0.08,6.61,13.39,20.16,26.28,32.82,39.21,45.23,50.60,58.15,64.96,-7.69,-7.97,0.23,3.69,-1.32,-3.39,-4.30,-5.09,2.23,1.30,0.01,-0.80,-1.50,1.00,2.42,2.72,3.27,4.80,5.02,3.46,3.78,0.3,2.3,-24.6,31.7,2.1,0.9,2.7,4.8,0.8,2.6,1.9,-1.6,2.1,5.8,2.1,1.9,2.1,2.9,2.1,1.1,3.0,64.6,-105.5,-139.3,101.0,-66.9,-168.8,-36.9,162.8,-121.3,0.2,-48.0,-146.9,-168.2,-51.8,-74.1,148.1,-40.8,72.6,-10.2,162.3,178.0,1.7,-177.7,-2.7,20.7,1.4,1.3,1.1,-178.3,0.8,0.7,0.9,0.8,-178.8,0.7,1.1,1.0,0.8,-2.2,-177.0,1.3,2.7,0.12,-0.17,-0.04,0.77,-0.16,0.12,-0.07,0.04,-0.01,-0.11,-0.06,-0.01,-0.01,0.00,0.03,0.08,-0.07,0.00,-0.01,0.02,0.16,-0.08,-0.13,-0.07,-0.93,0.15,0.20,0.21,0.16,-0.07,-0.06,-0.09,-0.06,-0.07,0.02,0.01,-0.02,-0.05,-0.21,-0.03,0.02,-0.13,NC

In [ ]:
total_data=total_data.replace('C*', 0)
total_data=total_data.replace('NC*', 1)
total_data=total_data.replace('C', 2)
total_data=total_data.replace('NC', 3)
total_data

,3ad,4ad,5ad,6ad,7ad,8ad,9ad,10ad,11ad,12ad,13ad,14ad,15ad,16ad,17ad,18ad,19ad,20ad,21ad,22ad,23ad,3be,4be,5be,6be,7be,8be,9be,10be,11be,12be,13be,14be,15be,16be,17be,18be,19be,20be,21be,22be,23be,3in,4in,5in,6in,7in,8in,9in,10in,11in,12in,13in,14in,15in,16in,17in,18in,19in,20in,21in,22in,23in,3og,4og,5og,6og,7og,8og,9og,10og,11og,12og,13og,14og,15og,16og,17og,18og,19og,20og,21og,22og,23og,3pl,4pl,5pl,6pl,7pl,8pl,9pl,10pl,11pl,12pl,13pl,14pl,15pl,16pl,17pl,18pl,19pl,20pl,21pl,22pl,23pl,3re,4re,5re,6re,7re,8re,9re,10re,11re,12re,13re,14re,15re,16re,17re,18re,19re,20re,21re,22re,23re,3rl,4rl,5rl,6rl,7rl,8rl,9rl,10rl,11rl,12rl,13rl,14rl,15rl,16rl,17rl,18rl,19rl,20rl,21rl,22rl,23rl,3sr,4sr,5sr,6sr,7sr,8sr,9sr,10sr,11sr,12sr,13sr,14sr,15sr,16sr,17sr,18sr,19sr,20sr,21sr,22sr,23sr,3st,4st,5st,6st,7st,8st,9st,10st,11st,12st,13st,14st,15st,16st,17st,18st,19st,20st,21st,22st,23st,3se,4se,5se,6se,7se,8se,9se,10se,11se,12se,13se,14se,15se,16se,17se,18se,19se,20se,21se,22se,23se,3sg,4sg,5sg,6sg,7sg,8sg,9sg,10sg,11sg,12sg,13sg,14sg,15sg,16sg,17sg,18sg,19sg,20sg,21sg,22sg,23sg,3sh,4sh,5sh,6sh,7sh,8sh,9sh,10sh,11sh,12sh,13sh,14sh,15sh,16sh,17sh,18sh,19sh,20sh,21sh,22sh,23sh,3tt,4tt,5tt,6tt,7tt,8tt,9tt,10tt,11tt,12tt,13tt,14tt,15tt,16tt,17tt,18tt,19tt,20tt,21tt,22tt,23tt,3tp,4tp,5tp,6tp,7tp,8tp,9tp,10tp,11tp,12tp,13tp,14tp,15tp,16tp,17tp,18tp,19tp,20tp,21tp,22tp,23tp,3tw,4tw,5tw,6tw,7tw,8tw,9tw,10tw,11tw,12tw,13tw,14tw,15tw,16tw,17tw,18tw,19tw,20tw,21tw,22tw,23tw,3xp,4xp,5xp,6xp,7xp,8xp,9xp,10xp,11xp,12xp,13xp,14xp,15xp,16xp,17xp,18xp,19xp,20xp,21xp,22xp,23xp,3yp,4yp,5yp,6yp,7yp,8yp,9yp,10yp,11yp,12yp,13yp,14yp,15yp,16yp,17yp,18yp,19yp,20yp,21yp,22yp,23yp,Outcome
1,7.9,7.9,7.7,8.9,8.4,9.0,10.6,14.8,17.8,20.6,24.4,27.6,24.0,20.4,16.5,12.6,10.7,10.6,10.2,8.0,6.9,-5.9,3.5,12.1,0.6,26.4,3.6,4.9,2.5,2.8,1.3,5.8,2.2,1.6,-0.4,1.1,2.5,-3.9,-3.0,-10.3,-14.0,-17.8,42.6,-82.5,-78.6,-1.9,-29.2,35.1,4.3,-30.2,14.9,21.0,-19.7,-10.3,-11.9,19.6,17.3,-10.0,22.7,17.9,20.9,36.9,40.5,69.8,131.3,-143.7,49.9,4.7,18.0,87.8,152.4,-135.6,-69.7,1.0,70.5,137.4,-149.7,-84.8,-13.5,46.4,96.0,143.7,-128.3,-65.5,18.4,25.0,-32.6,79.1,-166.4,-5.8,-4.5,0.8,-11.2,-11.0,-7.2,-4.1,3.6,-11.4,-12.3,-2.7,5.8,16.0,30.8,-38.0,-38.9,0.27,0.14,1.00,2.86,0.71,0.27,0.31,0.20,0.18,0.24,0.22,0.24,0.22,0.21,0.22,0.21,0.39,0.31,0.23,0.24,0.31,-4.1,-0.5,50.6,-62.0,58.4,-3.6,0.9,-0.8,-3.4,2.1,-3.9,3.7,0.1,-3.9,2.3,-3.4,-9.2,-9.3,-3.7,1.4,5.4,2.09,0.04,0.64,4.88,17.61,0.42,0.16,0.63,0.11,-0.07,0.01,0.07,-0.41,0.75,0.50,-0.18,-0.35,-1.67,-6.01,2.27,2.16,1.24,-0.13,3.00,-3.22,-0.08,-0.25,0.64,-0.08,-0.48,0.11,-0.14,0.48,-0.13,-0.72,0.29,-0.06,1.59,0.65,0.10,-1.31,-0.57,-0.42,-0.09,2.37,-0.39,-1.92,-0.02,0.22,-0.02,-0.45,0.24,-0.28,0.52,0.05,-0.06,-0.07,0.03,0.63,0.17,0.11,0.53,1.05,-58.25,-48.98,-48.87,-25.60,-8.32,-32.20,-25.78,-18.86,-13.15,-6.44,0.09,6.81,13.35,19.41,26.00,32.53,39.00,44.50,48.23,49.98,58.40,-20.83,-25.08,0.18,-14.84,2.89,-3.25,-3.94,-4.32,0.30,0.78,0.01,-0.57,0.02,2.98,2.86,3.15,3.09,-2.87,1.84,23.79,21.17,5.5,4.8,9.1,-22.5,4.6,0.3,0.4,4.3,-1.6,3.1,-1.1,1.7,3.5,0.8,2.3,1.0,-3.2,4.7,-1.6,-3.4,-5.1,161.0,-21.2,-145.0,-101.8,-100.1,102.7,103.4,-109.8,112.8,128.0,-31.3,167.2,71.6,167.3,139.0,-42.9,155.3,139.0,159.3,25.0,41.1,-0.3,-174.3,-28.0,-37.1,3.1,0.9,1.4,-178.5,0.8,1.3,1.6,0.2,-178.1,1.3,1.7,1.7,-5.2,-9.0,-176.9,0.6,0.8,0.01,0.02,0.07,-0.15,-0.82,0.03,0.09,-0.05,0.01,0.08,-0.05,-0.01,-0.01,0.09,0.32,-0.24,0.57,0.31,-0.18,0.02,0.08,0.38,0.25,-0.52,-0.40,-0.60,-0.39,-0.28,-0.14,0.13,-0.07,-0.07,-0.13,0.03,0.23,0.31,0.41,0.81,1.66,1.76,-1.69,-2.19,0
2,11.6,11.1,10.3,11.1,9.3,9.7,11.0,15.0,17.7,20.1,23.1,26.1,24.0,21.4,17.6,13.3,11.5,11.5,11.4,9.0,7.7,-9.2,5.8,36.7,37.7,28.5,3.3,4.7,2.3,2.3,1.8,5.4,2.5,1.5,-0.6,0.9,3.6,-4.2,-8.6,-15.7,-15.0,-20.1,30.3,-56.1,-97.3,-14.0,-31.0,17.2,26.1,-29.7,14.1,21.4,-15.0,-13.7,-11.7,20.1,17.8,-15.2,25.1,30.8,32.6,39.4,49.2,78.4,141.3,-135.0,58.1,-2.2,15.9,86.9,151.3,-136.2,-69.4,0.7,70.3,138.1,-148.6,-84.5,-11.2,47.6,94.2,134.7,-138.3,-74.5,14.3,18.2,-33.7,33.8,-158.7,-3.1,-3.5,3.7,-12.7,-11.0,-6.7,-2.9,3.8,-13.3,-14.9,-5.1,3.3,12.9,34.8,-35.0,-36.1,0.26,0.14,2.60,2.37,0.72,0.26,0.30,0.22,0.18,0.24,0.22,0.24,0.21,0.20,0.22,0.21,0.34,0.33,0.25,0.25,0.31,-5.5,0.7,43.6,-63.4,67.3,-3.4,1.4,-2.3,-3.3,1.9,-3.8,3.4,0.8,-4.2,2.7,-3.5,-9.9,-7.9,-7.0,1.9,4.8,2.40,-0.16,9.61,2.69,17.52,0.48,0.08,0.72,0.00,-0.03,0.01,0.05,-0.44,0.71,0.49,-0.19,-0.63,-3.15,-7.77,2.89,3.07,1.21,-0.14,3.65,-3.87,-0.03,-0.15,0.69,0.01,-0.49,-0.01,-0.02,0.48,-0.19,-0.75,0.21,-0.14,1.56,0.72,0.18,-1.23,-0.55,-0.66,0.02,4.02,-2.36,-1.90,0.06,0.19,-0.02,-0.38,0.29,-0.33,0.44,0.04,-0.07,-0.11,0.01,0.84,0.44,-0.01,0.79,1.21,-57.62,-48.61,-49.76,-26.67,-8.56,-32.27,-25.82,-18.88,-13.14,-6.45,0.11,6.81,13.36,19.40,26.00,32.62,39.07,44.78,49.32,49.47,57.91,-24.85,-27.37,5.87,-33.20,6.59,-2.78,-3.80,-4.34,0.15,0.67,0.01,-0.48,0.10,2.88,2.55,2.73,2.75,-4.23,-2.18,26.28,23.85,3.5,1.4,51.3,-77.4,5.6,1.3,1.1,5.4,-1.5,2.1,-0.4,1.7,2.6,0.3,1.6,1.0,-3.7,5.2,-1.7,-3.3,-5.0,160.1,-1.8,-132.4,-112.8,-107.3,115.7,102.5,-87.1,126.5,140.3,-24.3,130.0,41.9,173.3,152.1,-26.0,161.2,147.6,161.1,12.9,36.3,-0.3,-175.2,-52.7,-2.3,7.2,0.6,1.3,-178.2,0.6,1.4,1.5,0.4,-178.1,1.3,1.4,1.9,-5.0,-6.9,-178.2,0.6,1.0,-0.02,0.04,0.49,0.17,-0.80,-0.00,0.06,-0.04,0.02,0.08,-0.06,-0.00,0.00,0.08,0.35,-0.36,0.64,0.33,-0.23,0.01,-0.00,-0.38,-0.32,-0.60,0.87,-1.12,-0.52,-0.32,-0.14,0.08,-0.09,-0.04,-0.11,0.01,0.27,0.43,0.52,0.96,1.93,2.33,-1.96,-2.31,0
3,6.9,6.5,6.2,7.8,8.3,9.9,11.5,15.4,18.2,20.2,23.6,26.9,23.6,20.8,17.6,13.6,11.7,11.4,10.8,8.2,7.0,-8.4,16.9,36.2,3.9,28.2,2.7,5.7,2.7,2.9,1.5,5.6,2.5,2.1,0.9,1.6,2.4,-4.5,-5.6,-8.3,-13.8,-20.7,83.2,-103.6,-96.7,3.0,-27.3,18.6,10.3,-33.9,9.9,18.1,-15.4,-10.2,-13.1,14.8,10.7,-9.8,20.2,24.2,22.0,32.2,48.0,84.8,144.6,-129.6,74.8,-7.8,17.3,87.3,152.8,-135.3,-70.2,1.1,71.1,137.2,-150.3,-84.8,-13.4,46.3,91.7,125.4,-142.0,-80.0,14.1,20.9,-24.3,55.8,-149.1,-2.9,-3.9,0.2,-12.0,-11.9,-7.6,-4.9,4.2,-11.8,-14.2,-3.9,4.8,12.6,31.1,-29.3,-32.0,0.28,0.46,2.94,1.55,0.86,0.26,0.30,0.22,0.17,0.24,0.22,0.24,0.22,0.21,0.22,0.21,0.34,0.72,0.31,0.26,0.33,-4.5,-1.0,45.5,-76.7,71.2,-4.1,-0.0,-2.2,-3.1,2.7,-3.9,2.2,0.7,-3.9,3.0,-2.7,-8.6,-6.1,2.2,1.8,5.6,2.38,-3.30,7.68,5.72,19.92,0.74,0.04,0.65,0.13,-0.03,0.01,0.05,-0.40,0.58,0.46,-0.21,-0.22,-2.20,-6.13,3.35,3.45,1.09,-0.10,2.57,-2.49,0.02,-0.29,0.72,-0.04,-0.50,0.17,-0.20,0.49,-0.13,-0.77,0.21,-0.04,1.55,0.68,-0.45,-1.10,-0.65,-0.62,0.02,4.45,-2.60,-1.96,-0.07,0.06,-0.01,-0.36,0.22,-0.25,0.41,0.03,0.07,-0.02,0.10,1.08,0.47,-0.10,0.75,0.96,-58.04,-48.72,-49.60,-33.77,-10.44,-32.26,-25.83,-18.89,-13.17,-6.46,0.06,6.84,13.34,19.48,26.04,32.56,38.98,44.98,50.09,49.98,58.05,-24.52,-28.08,9.61,-26.53,11.12,-2.76,-3.87,-4.25,0.22,0.82,0.02,-0.68,-0.06,2.94,2.74,3.27,3.61,-3.12,-4.36,24.94,24.24,5.2,-0.7,32.2,-76.9,7.6,1.4,0.5,3.5,-1.7,3.2,-1.9,1.9,3.2,0.6,2.2,1.3,-3.2,1.8,8.3,-2.4,-4.8,-165.1,-16.2,-114.5,-135.4,-105.5,108.8,109.8,-98.5,121.3,134.6,-30.5,111.2,77.8,162.7,138.6,-25.8,158.2,151.4,154.8,1.4,32.6,0.1,-174.9,-72.2,-23.1,15.3,0.8,1.4,-178.4,0.7,1.4,1.7,0.6,-177.7,1.4,1.8,1.8,-3.3,-9.3,-177.5,1.0,1.0,-0.06,0.45,0.07,-0.43,-1.60,-0.00,0.11,-0.05,0.03,0.05,-0.03,-0.01,-0.02,0.09,0.24,-0.25,0.45,0.11,0.01,-0.09,-0.06,0.69,0.40,-0.98,1.26,-1.11,-0.49,-0.29,-0.15,0.07,-0.09,-0.04,-0.10,0.03,0.16,0.30,0.40,0.78,1.86,1.99,-1.65,-2.06,0
4,6.8,7.3,7.5,9.7,11.1,11.4,11.8,14.8,17.0,20.6,24.1,23.9,21.2,19.2,18.4,16.1,13.4,11.0,9.9,8.5,8.2,-16.3,21.2,26.1,153.2,17.6,6.4,-2.7,2.3,2.1,3.0,3.5,3.0,0.0,-2.9,5.9,-2.0,-3.1,-2.3,-22.7,-1.6,10.6,68.8,-84.4,-90.2,-58.3,-21.5,81.2,45.6,-47.3,20.0,-0.8,-4.1,-23.2,-13.2,16.6,-2.7,12.0,21.5,15.7,35.9,-0.7,-43.2,68.1,127.2,-143.3,31.6,-2.8,15.6,84.5,152.3,-130.8,-64.0,1.8,66.8,132.2,-152.1,-82.7,-12.3,47.7,99.6,142.5,-130.9,-66.9,14.9,15.5,-25.1,22.1,-165.7,-7.5,7.2,8.2,-11.8,-7.1,-8.5,1.5,14.2,-12.3,-12.3,-4.3,-2.2,8.2,28.7,-33.9,-32.2,0.28,0.38,2.13,3.22,0.48,0.25,0.19,0.22,0.26,0.22,0.19,0.23,0.16,0.26,0.26,0.21,0.34,0.28,0.28,0.25,0.35,-5.2,-3.2,36.8,-61.9,69.3,-5.2,-1.4,-1.7,-1.0,-2.7,6.0,-5.8,-0.4,2.5,-3.0,-4.6,-9.6,-10.9,0.3,2.6,-1.5,2.93,-4.07,4.81,0.76,12.72,0.62,0.78,0.12,-0.35,0.01,-0.00,0.21,-0.14,0.53,0.74,0.05,-1.13,-2.26,-12.53,2.35,4.07,0.67,-0.08,4.70,-4.69,-0.24,0.56,0.20,-0.10,-0.47,-0.60,0.52,0.54,-0.10,-0.24,-0.47,0.18,1.39,0.55,-0.23,-0.78,-0.52,-0.48,0.03,3.65,-2.37,-1.67,-0.21,-0.00,0.01,0.70,-0.47,0.51,-0.71,0.08,-0.06,0.20,-0.17,0.87,0.25,-0.00,0.50,0.68,-61.05,-50.85,-49.12,-19.99,-6.08,-32.26,-25.94,-19.03,-12.83,-6.39,0.08,6.59,13.03,19.72,26.19,32.72,38.89,44.35,47.67,53.30,60.19,-16.03,-24.06,5.62,-37.01,3.00,-3.63,-3.68,-4.60,1.01,0.70,0.03,-0.11,0.82,1.97,1.70,2.18,2.70,-3.66,-0.31,20.58,18.37,7.8,1.4,60.7,-73.5,6.4,1.6,0.6,3.9,1.4,1.5,4.2,0.8,2.2,2.7,0.3,2.9,-3.5,6.1,3.6,-1.7,0.3,129.1,-25.5,-132.2,-98.1,-104.6,93.8,96.2,-114.3,-141.5,-89.7,75.0,-44.6,51.3,116.2,-157.0,157.7,157.2,129.6,165.6,-167.5,-151.2,-0.4,-176.9,-37.4,5.4,0.0,0.9,0.5,-178.8,1.0,0.9,0.4,0.2,-179.1,0.8,1.4,0.1,-3.6,-7.2,-177.1,1.3,2.6,-0.29,0.68,0.23,0.36,-0.40,-0.03,0.01,-0.03,0.04,0.00,0.00,-0.05,0.01,0.01,0.03,0.25,0.48,0.32,-0.31,-0.04,-0.04,0.95,0.70,-1.28,1.19,-0.77,-0.48,-0.33,-0.19,-0.03,0.02,-0.17,0.00,-0.17,0.19,0.36,0.62,0.77,1.52,1.65,-1.34,-1.27,0
5,9.1,10.3,9.3,10.8,10.9,10.0,10.1,13.9,17.6,21.1,24.7,24.5,22.1,20.4,18.6,14.7,12.2,11.0,12.3,11.3,10.6,-11.5,10.7,15.6,1.4,35.0,6.6,-3.3,2.8,-0.1,2.6,3.6,3.1,0.0,-2.0,4.1,-1.6,-3.1,3.0,-13.9,-5.6,7.0,42.9,-58.1,-84.7,46.3,-54.7,72.7,59.0,-56.0,37.7,0.9,-6.8,-26.2,-10.3,20.1,1.1,12.9,18.5,-0.4,21.1,14.8,-21.2,76.7,133.7,-141.7,24.1,-7.6,15.5,83.9,153.9,-130.7,-62.8,2.5,65.5,132.1,-153.4,-82.4,-12.5,46.5,97.8,146.0,-135.3,-73.8,16.8,19.8,-30.3,39.4,-134.4,-5.6,7.2,7.3,-11.0,-8.7,-8.4,1.8,15.5,-13.2,-12.1,-5.2,-4.0,4.7,21.8,-30.8,-36.9,0.27,0.24,2.28,1.93,0.95,0.27,0.20,0.21,0.27,0.22,0.19,0.24,0.16,0.26,0.25,0.22,0.35,0.30,0.29,0.24,0.36,-3.4,-5.3,31.8,-77.3,66.4,-5.7,-1.5,-1.0,-2.2,-3.3,6.3,-5.7,-0.4,1.9,-1.8,-3.6,-8.3,-10.3,4.4,-0.9,-1.1,2.68,-1.60,4.04,8.95,22.54,1.41,0.73,0.20,-0.74,-0.12,-0.01,0.06,-0.16,0.80,0.59,0.26,-0.48,-0.61,-10.40,2.65,3.68,0.67,-0.05,3.48,-3.20,-0.33,0.34,0.31,-0.13,-0.29,-0.55,0.49,0.35,-0.10,-0.34,-0.27,-0.09,1.17,0.39,-0.27,-0.77,-0.67,-0.08,0.10,3.20,-2.62,-1.74,-0.21,0.09,-0.02,0.47,-0.45,0.49,-0.48,0.10,-0.16,0.21,-0.18,0.90,0.26,-0.09,0.10,0.27,-61.20,-51.28,-49.54,-30.54,-13.42,-32.10,-25.79,-18.79,-12.68,-6.25,0.04,6.53,13.03,19.61,26.25,32.64,38.81,44.45,48.12,53.20,60.24,-14.29,-22.23,0.83,-19.29,12.05,-4.19,-4.21,-5.09,1.60,0.82,0.03,-0.06,0.48,2.54,1.61,2.78,3.06,-2.63,1.20,18.11,17.13,8.2,0.2,32.5,-63.5,13.2,1.5,0.9,3.9,1.3,3.3,3.8,0.5,3.1,1.1,1.9,2.5,-2.6,5.9,4.5,-1.7,-0.3,123.9,-21.3,-131.0,-75.6,-116.2,-95.2,82.0,-129.8,163.9,-97.2,64.1,-45.6,65.2,-161.1,-154.7,156.5,158.8,96.8,162.3,54.3,-144.4,-0.3,-174.9,-42.1,1.1,15.2,1.5,0.5,-178.8,1.4,1.1,0.3,1.2,-179.1,0.8,1.5,0.1,-2.7,-8.2,-175.6,0.8,2.6,-0.06,0.34,0.13,-0.30,-1.32,-0.16,0.02,-0.04,0.08,0.03,0.00,-0.05,0.01,0.02,0.06,0.23,0.26,0.23,-0.08,-0.05,-0.15,0.58,0.42,-0.71,0.40,-0.69,-0.40,-0.34,-0.22,0.01,-0.01,-0.19,-0.00,-0.12,0.17,0.21,0.38,0.42,1.05,1.20,-0.71,-0.80,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,10.9,8.9,9.6,11.7,12.5,12.8,13.4,15.9,17.2,19.5,25.4,26.6,22.1,17.1,14.1,12.3,11.5,10.9,10.4,8.6,8.1,-1.8,6.8,3.2,17.5,3.3,0.5,3.0,-0.0,1.5,0.7,4.9,4.0,-0.1,0.2,-2.7,-1.2,8.7,-5.0,0.6,-2.1,-2.2,14.5,-43.0,-21.6,-39.6,34.7,11.0,-4.7,-8.4,6.8,6.6,-6.4,-16.0,-7.1,7.4,19.3,12.9,-21.4,15.0,1.2,11.6,10.9,43.2,112.6,-177.6,-6.3,-50.3,19.7,89.7,156.6,-129.3,-64.0,1.3,68.8,130.8,-153.9,-87.7,-17.9,55.7,112.1,-178.6,-107.8,-40.5,-6.2,-4.4,-1.2,174.9,-11.7,-6.7,-6.6,0.2,-6.3,-11.4,-7.7,-3.2,12.8,-17.4,-13.1,-9.1,-5.4,10.1,2.3,-19.0,-13.1,0.28,0.24,1.15,1.27,0.25,0.32,0.28,0.24,0.25,0.26,0.22,0.20,0.17,0.22,0.22,0.24,0.26,0.18,0.17,0.27,0.27,-2.4,-0.1,13.9,-16.4,-1.0,-0.4,4.3,0.2,3.4,-4.4,4.2,-0.3,-4.6,1.4,2.5,-2.5,-4.5,-0.8,-3.8,2.1,0.7,1.01,0.18,3.92,-13.48,0.40,-0.10,0.43,0.90,-0.34,-0.11,0.02,-0.01,-0.15,0.76,0.50,0.80,-1.01,-1.87,0.92,1.80,1.27,0.42,0.16,0.40,-2.41,-0.31,0.47,0.50,-0.17,-0.29,0.15,-0.22,0.35,-0.06,-0.49,-0.51,0.30,0.24,0.31,-0.34,-0.41,-0.20,-0.08,-0.27,-1.21,1.07,0.27,0.18,0.31,-0.04,0.20,-0.13,0.19,-0.27,0.10,-0.19,-0.21,-0.22,-0.31,-0.05,0.34,0.20,0.37,-64.06,-57.00,-49.57,0.29,-39.12,-32.65,-25.72,-18.93,-12.54,-6.55,0.06,6.74,13.17,19.41,25.92,32.77,39.45,44.99,50.59,57.48,64.49,-6.40,-7.95,-0.29,1.32,-4.09,-3.54,-3.05,-3.36,2.62,1.15,0.04,-0.83,-0.50,2.95,3.61,1.29,1.05,4.64,4.41,6.27,4.38,0.8,3.7,8.4,21.6,-1.1,-2.8,0.8,1.4,5.0,2.0,1.7,0.4,3.0,1.9,-2.4,0.7,5.1,2.0,-0.4,-0.8,-0.6,-95.2,40.7,-178.6,135.5,-59.9,-142.1,-72.0,80.7,138.8,177.1,70.7,-37.0,-82.8,-78.1,-178.8,-149.1,4.1,156.7,-1.1,-121.8,-88.9,0.8,177.4,-8.5,18.7,0.9,0.5,1.0,-179.1,1.3,1.9,1.3,0.5,-178.5,1.0,0.8,0.8,2.3,-177.8,-4.3,1.5,0.7,0.01,0.03,0.02,0.49,-0.11,0.06,-0.08,0.01,0.06,0.09,0.00,-0.01,0.01,-0.03,0.07,0.12,-0.19,0.07,0.00,-0.06,-0.12,0.03,0.08,-0.07,-0.69,-0.06,0.00,0.03,0.13,-0.09,-0.04,-0.11,-0.02,-0.10,0.17,0.14,0.11,0.09,0.15,0.04,-0.08,-0.08,2
69,11.7,9.9,10.8,12.7,12.6,12.5,13.0,15.5,16.5,19.0,24.6,25.8,22.3,17.8,14.4,12.5,11.5,10.7,10.1,8.1,7.8,2.2,6.6,0.2,15.2,2.9,0.3,3.2,2.4,3.1,1.3,4.4,4.2,-0.2,0.3,-1.4,-0.0,6.5,-0.6,1.1,-0.3,-1.7,-16.5,-42.1,-2.5,-47.1,25.5,13.6,0.7,-18.7,5.5,4.9,-6.4,-16.6,-8.2,7.6,12.7,7.0,-11.9,0.0,0.3,2.8,4.4,41.8,109.5,178.8,-7.4,-51.0,18.6,87.6,154.0,-131.8,-64.8,1.2,69.0,133.1,-151.5,-85.4,-16.9,55.7,116.2,-174.9,-105.0,-38.9,-6.9,-5.1,1.0,171.6,-12.7,-8.9,-7.9,1.0,-9.6,-11.4,-5.9,-2.5,13.8,-16.2,-13.5,-9.8,-5.1,8.9,-1.0,-18.3,-12.1,0.27,0.26,0.92,1.31,0.25,0.32,0.28,0.23,0.27,0.24,0.22,0.20,0.17,0.21,0.20,0.24,0.25,0.17,0.18,0.27,0.27,-1.9,0.9,23.9,-31.5,-1.4,-0.3,2.6,1.5,1.6,-2.7,3.5,-2.1,-4.2,1.0,3.0,-2.3,-3.5,0.5,-1.7,2.3,0.0,1.43,0.18,3.47,-14.99,0.26,-0.35,0.74,0.37,-0.18,-0.25,0.01,-0.03,-0.17,0.82,0.14,0.51,-0.45,-1.10,0.21,1.83,1.61,0.26,0.31,0.03,-2.34,-0.23,0.37,0.33,-0.11,-0.56,0.24,-0.28,0.59,-0.09,-0.31,-0.43,0.24,0.20,0.25,-0.48,-0.26,-0.24,-0.05,-0.24,-1.31,1.24,0.11,0.03,0.16,-0.04,0.26,-0.24,0.32,-0.32,0.08,-0.02,-0.04,-0.06,-0.32,-0.07,0.30,0.18,0.43,-64.03,-57.18,-49.60,0.90,-39.17,-32.62,-25.67,-19.07,-12.75,-6.50,0.05,6.69,13.10,19.58,25.90,32.65,39.33,45.01,50.85,57.79,64.39,-3.20,-6.38,-0.78,1.92,-3.29,-2.76,-2.40,-3.10,1.69,1.02,0.04,-0.61,0.26,2.17,3.54,1.78,1.29,4.36,3.58,4.56,4.64,2.3,2.4,20.0,32.1,-1.5,-2.5,0.9,1.2,3.3,2.2,1.9,0.9,2.4,4.4,-1.8,0.4,4.2,1.7,0.0,1.0,-0.1,10.3,21.7,-169.2,132.5,-57.9,-116.4,-37.1,134.9,-164.4,-160.6,38.5,-30.8,-121.9,-36.5,171.8,-160.6,-3.1,132.3,1.1,-160.3,-120.1,1.9,-5.6,-12.9,20.4,0.7,0.9,1.4,-178.8,1.3,1.4,1.3,0.5,-178.8,0.9,0.6,0.7,2.0,-178.9,0.6,2.5,0.6,-0.02,0.01,-0.01,0.48,-0.12,0.03,-0.07,-0.00,0.05,0.06,0.04,-0.02,0.02,-0.03,0.01,0.09,-0.17,0.05,-0.01,-0.00,-0.05,-0.12,-0.00,-0.09,-0.65,0.04,0.05,0.02,0.04,-0.03,0.02,-0.09,0.02,-0.06,0.06,0.06,0.06,0.07,0.05,0.05,-0.02,0.01,2
70,12.0,9.4,9.1,10.2,10.6,12.2,14.6,17.6,17.3,18.1,23.4,26.1,22.0,15.9,12.4,11.1,11.2,10.8,10.7,9.2,8.2,-2.1,3.9,6.5,21.0,3.6,3.0,2.8,-0.0,2.2,2.9,4.2,4.2,3.4,1.9,1.5,0.8,3.5,-2.3,0.4,-2.2,-1.2,-1.7,-8.3,-45.9,-15.3,31.1,4.5,-14.9,-5.0,8.2,11.5,-4.6,-16.7,-18.7,4.1,4.1,3.5,-1.6,6.7,0.8,20.6,9.6,49.7,117.5,-172.3,-9.0,-40.2,27.0,91.1,156.5,-132.5,-64.0,3.6,70.5,134.7,-153.3,-87.7,-25.0,43.7,108.0,173.9,-111.5,-46.2,-12.1,-5.7,-2.7,169.9,-9.0,-10.8,4.0,10.9,-5.9,-10.7,-13.8,-7.5,-4.0,-0.9,-8.1,-0.5,-2.0,8.4,8.9,-12.5,-8.3,0.31,0.27,1.17,1.49,0.27,0.32,0.24,0.22,0.25,0.23,0.23,0.25,0.24,0.25,0.23,0.21,0.25,0.20,0.21,0.30,0.30,-1.9,3.6,25.3,-29.4,-1.2,1.0,-1.3,1.8,2.1,1.9,0.6,1.0,0.5,1.9,-2.8,1.9,-1.0,-5.0,-2.9,-5.1,0.0,-2.12,3.72,4.76,-16.11,0.88,-0.42,0.95,0.20,-0.01,-0.05,0.01,-0.05,0.05,0.26,0.06,0.15,-1.05,-1.18,0.94,2.91,-0.20,0.47,0.13,0.68,-2.50,0.03,0.24,0.43,-0.07,-0.69,-0.26,0.25,0.69,-0.20,-0.45,-0.17,-0.07,0.38,0.29,-0.24,-0.54,0.10,0.15,0.02,-1.12,1.23,-0.05,0.07,-0.06,-0.12,0.12,0.06,0.01,-0.16,-0.06,0.07,-0.02,0.09,-0.32,0.18,-0.06,-0.18,0.00,-63.91,-56.80,-50.32,1.62,-39.01,-32.68,-26.18,-19.39,-13.09,-6.53,-0.08,6.61,13.39,20.16,26.28,32.82,39.21,45.23,50.60,58.15,64.96,-7.69,-7.97,0.23,3.69,-1.32,-3.39,-4.30,-5.09,2.23,1.30,0.01,-0.80,-1.50,1.00,2.42,2.72,3.27,4.80,5.02,3.46,3.78,0.3,2.3,-24.6,31.7,2.1,0.9,2.7,4.8,0.8,2.6,1.9,-1.6,2.1,5.8,2.1,1.9,2.1,2.9,2.1,1.1,3.0,64.6,-105.5,-139.3,101.0,-66.9,-168.8,-36.9,162.8,-121.3,0.2,-48.0,-146.9,-168.2,-51.8,-74.1,148.1,-40.8,72.6,-10.2,162.3,178.0,1.7,-177.7,-2.7,20.7,1.4,1.3,1.1,-178.3,0.8,0.7,0.9,0.8,-178.8,0.7,1.1,1.0,0.8,-2.2,-177.0,1.3,2.7,0.12,-0.17,-0.04,0.77,-0.16,0.12,-0.07,0.04,-0.01,-0.11,-0.06,-0.01,-0.01,0.00,0.03,0.08,-0.07,0.00,-0.01,0.02,0.16,-0.08,-0.13,-0.07,-0.93,0.15,0.20,0.21,0.16,-0.07,-0.06,-0.09,-0.06,-0.07,0.02,0.01,-0.02,-0.05,-0.21,-0.03,0.02,-0.13,3

In [ ]:
z = total_data['Outcome']
X=total_data.drop(['Outcome'], axis=1)
y=total_data['Outcome']

In [ ]:
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# List of 20 predetermined random seeds
random_seeds = [685641, 249077, 18533, 426353, 622463, 103321, 396546, 427173, 286636, 335318]

# Iterate through the random seeds
for i, random_seed in enumerate(random_seeds, start=1):
    np.random.seed(random_seed)  # Set the random seed

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    # Random Forest classifier
    rf = RandomForestClassifier(bootstrap=False,
                                      max_depth=4,
                                      max_features='sqrt',
                                      min_samples_leaf=1,
                                      min_samples_split=2,
                                      n_estimators=89,
                                      random_state=random_seed)
    # Fix the variable name

    # Perform Recursive Feature Elimination with Cross-Validation
    rfecv = RFECV(estimator=rf, cv=10)  # Set the number of cross-validations to 5 (default)
    X_train_selected = rfecv.fit_transform(X_train, y_train)

    # Get the selected features' indices
    selected_feature_indices = rfecv.get_support(indices=True)

    # Subset the original feature names using the selected indices
    selected_features = X_train.columns[selected_feature_indices]

    # Get feature importances from RFECV
    feature_importances = rfecv.estimator_.feature_importances_

    # Set the desired number of features
    num_features = 36  # Replace 10 with the desired number of features

    # Create a DataFrame with selected features and importances
    coeff_df = pd.DataFrame({'Feature': selected_features[:num_features], 'Importance': feature_importances[:num_features]})

    # Save the DataFrame as a CSV file with a different name for each random seed
    filename = f'TP53_RFECV_{i}.csv'
    coeff_df.to_csv(filename, index=False)

In [ ]:
coeff_df

   Feature  Importance
0      9ad    0.004887
1     10ad    0.011461
2     11ad    0.003909
3     12ad    0.002375
4     13ad    0.001236
5     14ad    0.000762
6     15ad    0.000000
7     16ad    0.000487
8     17ad    0.006500
9     18ad    0.008844
10    19ad    0.002295
11    20ad    0.000000
12    21ad    0.001458
13    22ad    0.000938
14    23ad    0.000422
15     3be    0.007618
16     4be    0.001782
17     5be    0.000496
18     6be    0.001506
19     7be    0.011353
20     8be    0.000703
21     9be    0.001413
22    10be    0.000000
23    11be    0.000000
24    12be    0.000000
25    13be    0.005381
26    14be    0.001742
27    15be    0.000000
28    16be    0.000000
29    17be    0.002111
30    18be    0.001773
31    20be    0.007538
32    22be    0.012172
33    23be    0.003011
34     4in    0.000395
35     5in    0.001520